"""Generated research-note pipeline for archived documents."""

from __future__ import annotations

import logging
from datetime import datetime
from pathlib import Path

from pkp.config import get_config
from pkp.llm.client import generate_document_notes
from pkp.pipeline.proposals import _strip_leading_frontmatter
from pkp.storage.archive import ArchiveManager
from pkp.storage.db import db_context
from pkp.storage.models import Document
from pkp.vault.writer import (
    VaultWriterError,
    create_document_note,
    write_notes_section,
)

logger = logging.getLogger(__name__)

NOTE_FAILURE_PLACEHOLDER = (
    "*Note generation failed — run `pkp generate-notes {sha256}` to retry.*"
)


async def generate_notes(doc_sha256: str) -> bool:
    """Generate and write research notes for one archived document."""
    config = get_config()
    if config.archive_path is None:
        logger.error(
            "note generation archive path not configured sha256=%s", doc_sha256
        )
        return False
    if config.vault_path is None:
        logger.error("note generation vault path not configured sha256=%s", doc_sha256)
        return False

    async with db_context() as db:
        doc = await db.get_document(doc_sha256)

    if doc is None:
        logger.warning("note generation document not found sha256=%s", doc_sha256)
        return False

    try:
        await _ensure_vault_note(config.vault_path, doc)
    except VaultWriterError as exc:
        logger.warning(
            "note generation scaffold unavailable sha256=%s: %s", doc_sha256, exc
        )
        return False
    except Exception as exc:
        logger.warning(
            "note generation scaffold failed unexpectedly sha256=%s: %s",
            doc_sha256,
            exc,
        )
        return False

    archive = ArchiveManager(config.archive_path)
    normalized_text = archive.read_normalized(doc_sha256)
    if normalized_text is None:
        logger.warning("note generation normalized file missing sha256=%s", doc_sha256)
        _write_failure_placeholder(config.vault_path, doc)
        return False

    body_text = _strip_leading_frontmatter(normalized_text).strip()
    notes = await generate_document_notes(
        body_text=body_text,
        endpoint=config.llm_endpoint,
        model=config.llm_model,
    )
    if notes is None:
        logger.warning(
            "note generation failed sha256=%s title=%r", doc.sha256, doc.title
        )
        _write_failure_placeholder(config.vault_path, doc)
        return False

    final_notes = _append_generation_metadata(notes, config.llm_model)
    note_path = write_notes_section(config.vault_path, doc, final_notes)
    word_count = len(final_notes.split())
    logger.info(
        "note generation written sha256=%s title=%r note_words=%s path=%s",
        doc.sha256,
        doc.title,
        word_count,
        note_path,
    )
    return True


async def _ensure_vault_note(vault_path: Path, doc: Document) -> Path:
    """Create a vault scaffold when the stored note path is missing."""
    note_path = _existing_note_path(vault_path, doc)
    if note_path is not None and note_path.exists():
        return note_path

    note_path = create_document_note(vault_path, doc)
    doc.vault_path = str(note_path)
    async with db_context() as db:
        await db.mark_document_vault_path(doc.sha256, str(note_path))
    return note_path


def _existing_note_path(vault_path: Path, doc: Document) -> Path | None:
    """Return the stored note path when present."""
    if doc.vault_path is None:
        return None
    note_path = Path(doc.vault_path)
    if not note_path.is_absolute():
        note_path = vault_path / note_path
    return note_path


def _write_failure_placeholder(vault_path: Path, doc: Document) -> None:
    """Write the visible failure marker into the document note."""
    try:
        write_notes_section(
            vault_path,
            doc,
            NOTE_FAILURE_PLACEHOLDER.format(sha256=doc.sha256),
        )
    except Exception as exc:
        logger.warning(
            "note generation failure placeholder write failed sha256=%s: %s",
            doc.sha256,
            exc,
        )


def _append_generation_metadata(notes: str, model: str) -> str:
    """Append the visible model/date marker to generated notes."""
    generated_date = datetime.now().date().isoformat()
    return (
        f"{notes.strip()}\n\n"
        "---\n"
        f"*Generated by {model} on {generated_date} — edit freely*"
    )
